AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  MyBucketName:
    Description: Sonja-Bucket-IaC
    Type: String
    Default: sonja-iac-bucket
  
  QueName:
    Description: Sonja-SQS
    Type: String
    Default: sonja-sqs-iac

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  MyBucketResources:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
  
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueName
  
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro