AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  MyBucketName:
    Description: Sonja-Bucket-IaC
    Type: String
    Default: sonja-iac-bucket
  QueName:
    Description: Sonja-SQS
    Type: String
    Default: sonja-sqs-iac

Resources:
  MyBucketResources:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueName